### ISSUE TITLE
'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by rudnam** [bluaxees/Cloe#17]
![image](https://user-images.githubusercontent.com/70255485/212853993-db545dd4-bf8e-4ce8-9ab1-cab04bac1415.png)
I'm having this error when I try to open up cloe

Files:
![image](https://user-images.githubusercontent.com/70255485/212854292-a812a567-aa3c-4f48-93f6-f8a2e7c089a1.png)

**Comment by blueaxis** [comment]
Load model error usually happens due to weak/no internet connection. Did you have internet connection when you opened the app?

**Comment by RoYou17** [comment]
I've encountered the same issue even though my internet is good (95 Mbps download/ 40 Mbps up).

**Comment by blueaxis** [comment]
Should be fixed now. Please redownload the latest release
