### ISSUE TITLE
Nothing Happens After Selecting Area to OCR

### ISSUE THREAD

**Issue by BambiIcedTea** [bluaxees/Cloe#20]
Currently on Windows 11 and am able to run Cloe, access the settings, and it loads the MangaOCR model. When I press Alt + Q the screen is highlighted and I can select an area, but then nothing else happens.

Took a look at the video in the readme and can see that the selection / highlight is meant to stay for a short period and that the OCR'd text is meant to show up etc, but I don't get any of that.

Have tried ruling out OS language (EN-GB/JA-JP), system locale (UK/JP/Unicode), and multiple displays (2 x External/Built-in Only) in case they have any quirky effects, but no changes.

**Comment by blueaxis** [comment]
Releasing the left mouse button will hide the text preview (OCR'd text), so you have to hold it for a few milliseconds before the prediction shows up. If you are already doing this, can you please post a recording here?

**Comment by BambiIcedTea** [comment]
Ah! It would seem that it works when holding the mouse button down for a while, then it copies to the clipboard; I mustn't have been holding it down for long enough ... 

Thanks for sending me in the right direction!
